project:
  type: website

website:
  title: "HB2 Section by Section"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "No content, or portion thereof, represents an official position of any school district or school official"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd

format:
  html:
    theme: default
    css: swart-20250327.css
    # theme: [cerulean, swart-20250327.css]


